// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI operations (migrate, studio) use the direct (non-pooled)
    // connection - Supabase's pooler runs in pgbouncer transaction mode,
    // which doesn't support the prepared statements Prisma's migration
    // engine needs. The generated client at runtime still uses
    // DATABASE_URL (pooled) per schema.prisma, unaffected by this file.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"]!,
  },
});
